### ISSUE TITLE
 Document 2.5 to 2.6 upgrade path for templates

### ISSUE THREAD

**Issue by miguelsorianod** [3scale/3scale-operator#125]
Write documentation to upgrade from 2.5 to 2.6 release in templates.

For the moment the following should be documented:

- [x]  Migrate all DCs to use the new ServiceAccounts and migrate to be able to use RedHat registry #124
- [x]  Update existing ImageStream images
- [ ]  How to move DBs DCs to ImageStreams, also including the modification of the "postgresql" imagestream to use the tag formatting that we have in all the other ones #122 and #155
- [x]  Maybe some PostgreSQL template addition related change?  #129 --> No specific changes needed for upgrade
- [ ]  Remove WildcardRouter #135
- [ ]  Add/Modify new Zync-related changes #145 . What is observed as template changes related to this commit is the addition of the new elements and removal of default system routes (system-master, system-provider, system-developer, apicast-production, apicast-staging). The addition of new elements should be documented in the upgrade procedure but the removal of old routes probably not because the user might want to keep them
- [ ]  Redis Enterprise Support #114 related changes
- [ ]  Redis Sentinel Support #137 related changes

- [ ]  Apply Redis Sentinel environment variable fixes in backend-cron and backend-worker #133
